import type { Property } from "./types";

const photos = {
  modern: "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=1400&q=80",
  villa: "https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?auto=format&fit=crop&w=1400&q=80",
  bright: "https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?auto=format&fit=crop&w=1400&q=80",
  house: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1400&q=80",
  office: "https://images.unsplash.com/photo-1497366754035-f200968a6e72?auto=format&fit=crop&w=1400&q=80",
  apartment: "https://images.unsplash.com/photo-1600566753086-00f18fb6b3ea?auto=format&fit=crop&w=1400&q=80",
};

const seller = { id: "seller-1", name: "Mekdes Tesfaye", role: "broker" as const, agency: "Abay Homes", memberSince: "2023-04-12", activeListings: 12, phone: "+251 911 234 567", whatsapp: "+251911234567", verified: true, hostRating:4.8, reviewCount:42, responseRate:92, responseTime:"within 2 hours" };
export const properties: Property[] = [
  { id:"p1", slug:"sunlit-three-bedroom-apartment-bole-p1", title:"Sunlit three-bedroom apartment", description:"A calm, generously proportioned home with wide windows, warm finishes and a balcony overlooking a quiet Bole street. Backup generator, water reserve and 24-hour security are included.", propertyType:"Apartment", listingType:"sale", price:18500000, currency:"ETB", areaSqm:135, bedrooms:3, bathrooms:2, parkingSpaces:1, neighborhood:"Bole", subcity:"Bole", city:"Addis Ababa", latitude:8.995, longitude:38.789, image:photos.modern, images:[photos.modern, photos.bright, photos.apartment], verificationStatus:"fully_verified", furnished:false, hasElevator:true, hasGenerator:true, hasWaterTank:true, hasSecurity:true, hasBalcony:true, hasGarden:false, createdAt:"2026-08-12", seller },
  { id:"p2", slug:"garden-villa-old-airport-p2", title:"Private garden villa", description:"A private family villa set behind mature greenery, with bright living rooms and secure parking.", propertyType:"Villa", listingType:"sale", price:42500000, currency:"ETB", areaSqm:420, bedrooms:5, bathrooms:4, parkingSpaces:3, neighborhood:"Old Airport", subcity:"Nifas Silk-Lafto", city:"Addis Ababa", latitude:8.971, longitude:38.725, image:photos.villa, images:[photos.villa, photos.house], verificationStatus:"documents_reviewed", furnished:false, hasElevator:false, hasGenerator:true, hasWaterTank:true, hasSecurity:true, hasBalcony:true, hasGarden:true, createdAt:"2026-08-10", seller:{...seller,id:"seller-2",name:"Daniel Bekele",role:"owner",agency:undefined,activeListings:1} },
  { id:"p3", slug:"furnished-two-bed-kazanchis-p3", title:"Furnished city apartment", description:"Move-in-ready apartment close to offices, hotels and the light rail.", propertyType:"Apartment", listingType:"rent", price:85000, currency:"ETB", areaSqm:98, bedrooms:2, bathrooms:2, parkingSpaces:1, neighborhood:"Kazanchis", subcity:"Kirkos", city:"Addis Ababa", latitude:9.018, longitude:38.765, image:photos.bright, images:[photos.bright, photos.modern], verificationStatus:"location_verified", furnished:true, hasElevator:true, hasGenerator:true, hasWaterTank:true, hasSecurity:true, hasBalcony:false, hasGarden:false, createdAt:"2026-08-09", seller },
  { id:"p4", slug:"family-home-cmc-p4", title:"Quiet family home near CMC", description:"Comfortable detached home with a garden, water tank and room to grow.", propertyType:"House", listingType:"rent", price:120000, currency:"ETB", areaSqm:280, bedrooms:4, bathrooms:3, parkingSpaces:2, neighborhood:"CMC", subcity:"Yeka", city:"Addis Ababa", latitude:9.022, longitude:38.848, image:photos.house, images:[photos.house, photos.villa], verificationStatus:"identity_verified", furnished:false, hasElevator:false, hasGenerator:false, hasWaterTank:true, hasSecurity:true, hasBalcony:true, hasGarden:true, createdAt:"2026-08-06", seller:{...seller,id:"seller-3",name:"Selamawit Girma",agency:"Liya Properties"} },
  { id:"p5", slug:"creative-office-gerji-p5", title:"Flexible creative office", description:"Light-filled office floor with meeting rooms, reception and secure access.", propertyType:"Office", listingType:"rent", price:160000, currency:"ETB", areaSqm:210, bedrooms:0, bathrooms:2, parkingSpaces:3, neighborhood:"Gerji", subcity:"Bole", city:"Addis Ababa", latitude:9.002, longitude:38.82, image:photos.office, images:[photos.office], verificationStatus:"unverified", furnished:true, hasElevator:true, hasGenerator:true, hasWaterTank:true, hasSecurity:true, hasBalcony:false, hasGarden:false, createdAt:"2026-08-04", seller },
  { id:"p6", slug:"new-condominium-ayat-p6", title:"New-build condominium", description:"Efficient new condominium with clean finishes and excellent eastern-city access.", propertyType:"Condominium", listingType:"sale", price:7900000, currency:"ETB", areaSqm:82, bedrooms:2, bathrooms:1, parkingSpaces:1, neighborhood:"Ayat", subcity:"Lemi Kura", city:"Addis Ababa", latitude:9.035, longitude:38.89, image:photos.apartment, images:[photos.apartment, photos.bright], verificationStatus:"location_verified", furnished:false, hasElevator:true, hasGenerator:false, hasWaterTank:true, hasSecurity:true, hasBalcony:true, hasGarden:false, createdAt:"2026-08-01", seller },
  { id:"p7", slug:"serviced-two-bedroom-bole-p7", title:"Serviced two-bedroom in Bole", description:"A quiet, fully equipped stay near Atlas with reliable utilities, a dedicated workspace and secure access.", propertyType:"Apartment", listingType:"short_term_stay", price:2500, currency:"ETB", areaSqm:92, bedrooms:2, bathrooms:2, parkingSpaces:1, neighborhood:"Bole", subcity:"Bole", city:"Addis Ababa", latitude:9.006, longitude:38.782, image:photos.bright, images:[photos.bright,photos.modern,photos.apartment], verificationStatus:"fully_verified", furnished:true, hasElevator:true, hasGenerator:true, hasWaterTank:true, hasSecurity:true, hasBalcony:true, hasGarden:false, hasSolar:false,hasBackupBattery:true,waterTankCapacity:2000,fiberInternet:true,backupInternet:true,securityGuard:true,gatedCompound:true,cctv:true,fullyFurnished:true,kitchenEquipped:true,washingMachine:true,television:true,workspace:true,maxGuests:4,beds:3,bedTypes:["1 queen bed","2 single beds"],prices:[{type:"nightly_price",amount:2500},{type:"weekly_price",amount:16000},{type:"cleaning_fee",amount:500}],rules:{petsAllowed:false,smokingAllowed:false,partiesAllowed:false,childrenAllowed:true,checkInTime:"14:00",checkOutTime:"11:00"},rating:4.8,reviewCount:18,verifiedPhotos:true,verifiedLocation:true,verifiedAmenities:true,createdAt:"2026-08-13",seller },
  { id:"p8", slug:"furnished-consultant-suite-kazanchis-p8", title:"Furnished consultant suite", description:"Flexible medium-term home for visiting professionals, close to UNECA and central business offices.", propertyType:"Apartment", listingType:"medium_term_rent", price:18000, currency:"ETB", areaSqm:75, bedrooms:1, bathrooms:1, parkingSpaces:1, neighborhood:"Kazanchis", subcity:"Kirkos", city:"Addis Ababa", latitude:9.017, longitude:38.766, image:photos.apartment, images:[photos.apartment,photos.bright], verificationStatus:"location_verified", furnished:true,hasElevator:true,hasGenerator:true,hasWaterTank:true,hasSecurity:true,hasBalcony:false,hasGarden:false,fiberInternet:true,fullyFurnished:true,kitchenEquipped:true,washingMachine:true,workspace:true,maxGuests:2,beds:1,bedTypes:["1 queen bed"],prices:[{type:"weekly_price",amount:18000},{type:"monthly_price",amount:65000}],rules:{petsAllowed:false,smokingAllowed:false,partiesAllowed:false,childrenAllowed:true,checkInTime:"14:00",checkOutTime:"11:00"},rating:4.6,reviewCount:7,verifiedPhotos:true,verifiedLocation:true,verifiedAmenities:false,createdAt:"2026-08-11",seller },
];

export const neighborhoods = ["Bole", "Kazanchis", "CMC", "Saris", "Yeka", "Old Airport", "Gerji", "Jemo", "Ayat"];
export const formatPrice = (value:number) => new Intl.NumberFormat("en-US").format(value) + " ETB";
