"use client";
import {createContext,useContext,useEffect,useMemo,useState} from "react";
export type DemoRole="buyer"|"owner"|"broker"|"admin";type DemoUser={name:string;email:string;role:DemoRole}|null;
export type Inquiry={id:string;propertyId:string;propertyTitle:string;message:string;status:"new"|"read"|"responded"|"closed";createdAt:string};
export type Report={id:string;propertyId:string;propertyTitle:string;reason:string;description:string;status:"open"|"reviewing"|"resolved"|"dismissed";createdAt:string};
export type DemoListing={id:string;title:string;neighborhood:string;price:number;status:"draft"|"pending_review"|"published"|"rejected";createdAt:string};
type Value={ready:boolean;user:DemoUser;favorites:string[];inquiries:Inquiry[];reports:Report[];listings:DemoListing[];signIn:(email:string,role:DemoRole)=>void;signOut:()=>void;toggleFavorite:(id:string)=>void;sendInquiry:(x:Omit<Inquiry,"id"|"status"|"createdAt">)=>void;updateInquiry:(id:string,status:Inquiry["status"])=>void;submitReport:(x:Omit<Report,"id"|"status"|"createdAt">)=>void;updateReport:(id:string,status:Report["status"])=>void;addListing:(x:Omit<DemoListing,"id"|"status"|"createdAt">)=>void};
const Context=createContext<Value|null>(null);const storageKey="betoch-demo-state-v2";
export function DemoProvider({children}:{children:React.ReactNode}){const [ready,setReady]=useState(false);const [user,setUser]=useState<DemoUser>(null);const [favorites,setFavorites]=useState<string[]>([]);const [inquiries,setInquiries]=useState<Inquiry[]>([]);const [reports,setReports]=useState<Report[]>([]);const [listings,setListings]=useState<DemoListing[]>([]);useEffect(()=>{try{const x=JSON.parse(localStorage.getItem(storageKey)||"{}");setUser(x.user||null);setFavorites(x.favorites||[]);setInquiries(x.inquiries||[]);setReports(x.reports||[]);setListings(x.listings||[])}finally{setReady(true)}},[]);useEffect(()=>{if(ready)localStorage.setItem(storageKey,JSON.stringify({user,favorites,inquiries,reports,listings}))},[ready,user,favorites,inquiries,reports,listings]);const value=useMemo<Value>(()=>({ready,user,favorites,inquiries,reports,listings,signIn:(email,role)=>setUser({email,role,name:role==="admin"?"Platform Admin":role==="buyer"?"Abel Girma":"Mekdes Tesfaye"}),signOut:()=>setUser(null),toggleFavorite:id=>setFavorites(v=>v.includes(id)?v.filter(x=>x!==id):[...v,id]),sendInquiry:x=>setInquiries(v=>[{...x,id:crypto.randomUUID(),status:"new",createdAt:new Date().toISOString()},...v]),updateInquiry:(id,status)=>setInquiries(v=>v.map(x=>x.id===id?{...x,status}:x)),submitReport:x=>setReports(v=>[{...x,id:crypto.randomUUID(),status:"open",createdAt:new Date().toISOString()},...v]),updateReport:(id,status)=>setReports(v=>v.map(x=>x.id===id?{...x,status}:x)),addListing:x=>setListings(v=>[{...x,id:crypto.randomUUID(),status:"pending_review",createdAt:new Date().toISOString()},...v])}),[ready,user,favorites,inquiries,reports,listings]);return <Context.Provider value={value}>{children}</Context.Provider>}
export function useDemo(){const value=useContext(Context);if(!value)throw new Error("DemoProvider is missing");return value}
