-- Stay marketplace extension. Requests only: no payment, payout, escrow, or external calendar sync.
alter table public.properties drop constraint if exists properties_listing_type_check;
alter table public.properties add constraint properties_listing_type_check check(listing_type in ('sale','rent','long_term_rent','medium_term_rent','short_term_stay'));
alter table public.properties add column if not exists has_solar boolean not null default false, add column if not exists has_backup_battery boolean not null default false, add column if not exists water_tank_capacity integer check(water_tank_capacity>=0), add column if not exists fiber_internet boolean not null default false, add column if not exists backup_internet boolean not null default false, add column if not exists security_guard boolean not null default false, add column if not exists gated_compound boolean not null default false, add column if not exists cctv boolean not null default false, add column if not exists fully_furnished boolean not null default false, add column if not exists semi_furnished boolean not null default false, add column if not exists kitchen_equipped boolean not null default false, add column if not exists washing_machine boolean not null default false, add column if not exists television boolean not null default false, add column if not exists workspace boolean not null default false, add column if not exists air_conditioning boolean not null default false, add column if not exists heating boolean not null default false, add column if not exists max_guests smallint check(max_guests>0), add column if not exists beds smallint check(beds>=0), add column if not exists bed_types text[] not null default '{}', add column if not exists verified_host boolean not null default false, add column if not exists verified_photos boolean not null default false, add column if not exists verified_location boolean not null default false, add column if not exists verified_amenities boolean not null default false;
alter table public.profiles add column if not exists host_rating numeric(2,1) check(host_rating between 1 and 5), add column if not exists review_count integer not null default 0, add column if not exists response_rate numeric(5,2) check(response_rate between 0 and 100), add column if not exists response_time text, add column if not exists host_since date, add column if not exists phone_verified boolean not null default false, add column if not exists email_verified boolean not null default false, add column if not exists identity_verified boolean not null default false;
create table public.property_availability(id uuid primary key default gen_random_uuid(),property_id uuid not null references public.properties(id) on delete cascade,start_date date not null,end_date date not null,status text not null check(status in ('available','reserved','blocked','maintenance')),minimum_stay_days smallint not null default 1 check(minimum_stay_days>0),maximum_stay_days smallint check(maximum_stay_days>=minimum_stay_days),created_at timestamptz not null default now(),updated_at timestamptz not null default now(),check(end_date>=start_date));
create table public.property_pricing(id uuid primary key default gen_random_uuid(),property_id uuid not null references public.properties(id) on delete cascade,pricing_type text not null check(pricing_type in ('sale_price','monthly_price','weekly_price','nightly_price','cleaning_fee','security_deposit')),amount numeric(16,2) not null check(amount>=0),currency char(3) not null default 'ETB',created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(property_id,pricing_type));
create table public.property_rules(property_id uuid primary key references public.properties(id) on delete cascade,pets_allowed boolean not null default false,smoking_allowed boolean not null default false,parties_allowed boolean not null default false,children_allowed boolean not null default true,check_in_time time,check_out_time time);
create table public.booking_requests(id uuid primary key default gen_random_uuid(),property_id uuid not null references public.properties(id),guest_id uuid not null references public.profiles(id),host_id uuid not null references public.profiles(id),check_in date not null,check_out date not null,guest_count smallint not null check(guest_count>0),message text not null check(length(message) between 1 and 2000),status text not null default 'pending' check(status in ('pending','approved','rejected','cancelled','completed')),created_at timestamptz not null default now(),updated_at timestamptz not null default now(),check(check_out>check_in),check(guest_id<>host_id));
create table public.property_reviews(id uuid primary key default gen_random_uuid(),property_id uuid not null references public.properties(id),booking_request_id uuid not null unique references public.booking_requests(id),reviewer_id uuid not null references public.profiles(id),rating smallint not null check(rating between 1 and 5),title text not null check(length(title) between 2 and 120),review_text text not null check(length(review_text) between 2 and 2000),stay_type text not null check(stay_type in ('short_stay','medium_term','long_term')),created_at timestamptz not null default now());
create index availability_dates_idx on public.property_availability(property_id,start_date,end_date);create index booking_guest_idx on public.booking_requests(guest_id,status);create index booking_host_idx on public.booking_requests(host_id,status);create index reviews_property_idx on public.property_reviews(property_id,created_at desc);
alter table public.property_availability enable row level security;alter table public.property_pricing enable row level security;alter table public.property_rules enable row level security;alter table public.booking_requests enable row level security;alter table public.property_reviews enable row level security;
create policy "published stay details readable" on public.property_availability for select using(exists(select 1 from public.properties p where p.id=property_id and (p.status='published' or p.owner_id=auth.uid() or public.is_admin())));create policy "hosts manage availability" on public.property_availability for all using(exists(select 1 from public.properties p where p.id=property_id and (p.owner_id=auth.uid() or public.is_admin()))) with check(exists(select 1 from public.properties p where p.id=property_id and (p.owner_id=auth.uid() or public.is_admin())));
create policy "pricing readable" on public.property_pricing for select using(exists(select 1 from public.properties p where p.id=property_id and (p.status='published' or p.owner_id=auth.uid() or public.is_admin())));create policy "hosts manage pricing" on public.property_pricing for all using(exists(select 1 from public.properties p where p.id=property_id and (p.owner_id=auth.uid() or public.is_admin())));
create policy "rules readable" on public.property_rules for select using(exists(select 1 from public.properties p where p.id=property_id and (p.status='published' or p.owner_id=auth.uid() or public.is_admin())));create policy "hosts manage rules" on public.property_rules for all using(exists(select 1 from public.properties p where p.id=property_id and (p.owner_id=auth.uid() or public.is_admin())));
create policy "booking participants read" on public.booking_requests for select using(guest_id=auth.uid() or host_id=auth.uid() or public.is_admin());create policy "guest requests stay" on public.booking_requests for insert with check(guest_id=auth.uid() and status='pending' and host_id=(select owner_id from public.properties where id=property_id) and guest_count<=(select max_guests from public.properties where id=property_id));create policy "participants update booking" on public.booking_requests for update using(guest_id=auth.uid() or host_id=auth.uid() or public.is_admin());
create policy "published reviews readable" on public.property_reviews for select using(true);create policy "completed guest reviews" on public.property_reviews for insert with check(reviewer_id=auth.uid() and exists(select 1 from public.booking_requests b where b.id=booking_request_id and b.property_id=property_id and b.guest_id=auth.uid() and b.status='completed'));
