-- Betoch marketplace schema. All verification remains a manual admin workflow.
create extension if not exists pgcrypto;
create type public.user_role as enum ('buyer','owner','broker','admin');
create type public.property_status as enum ('draft','pending_review','published','rejected','sold','rented','archived');
create type public.verification_level as enum ('unverified','identity_verified','location_verified','documents_reviewed','fully_verified');
create type public.review_status as enum ('pending','approved','rejected');

create table public.profiles (
 id uuid primary key references auth.users(id) on delete cascade, name text not null, role user_role not null default 'buyer', profile_image text,
 phone text, whatsapp text, agency_name text, agency_description text, office_location text, bio text,
 verification_status verification_level not null default 'unverified', show_phone boolean not null default false, show_whatsapp boolean not null default false,
 suspended_at timestamptz, created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);
create table public.properties (
 id uuid primary key default gen_random_uuid(), owner_id uuid not null references public.profiles(id), slug text unique not null,
 title text not null check(length(title) between 3 and 160), description text not null default '' check(length(description)<=5000),
 property_type text not null check(property_type in ('apartment','house','villa','condominium','land','commercial','office','warehouse','other')),
 listing_type text not null check(listing_type in ('sale','rent')), price numeric(16,2) not null check(price>0), currency char(3) not null default 'ETB',
 area_sqm numeric(10,2) not null check(area_sqm>0), bedrooms smallint not null default 0 check(bedrooms>=0), bathrooms smallint not null default 0 check(bathrooms>=0), parking_spaces smallint not null default 0 check(parking_spaces>=0), floor_number smallint, total_floors smallint, year_built smallint,
 condition text check(condition in ('new','excellent','good','needs_renovation')), furnished boolean not null default false,
 has_elevator boolean not null default false, has_generator boolean not null default false, has_water_tank boolean not null default false,
 has_security boolean not null default false, has_balcony boolean not null default false, has_garden boolean not null default false,
 address_text text, city text not null default 'Addis Ababa', subcity text, neighborhood text, latitude double precision check(latitude between -90 and 90), longitude double precision check(longitude between -180 and 180), location_precision text not null default 'approximate' check(location_precision in ('exact','approximate')),
 status property_status not null default 'draft', verification_status verification_level not null default 'unverified', moderation_reason text,
 possible_duplicate boolean not null default false, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), published_at timestamptz,
 check(status <> 'published' or (subcity is not null and neighborhood is not null and latitude is not null and longitude is not null))
);
create table public.property_images (id uuid primary key default gen_random_uuid(), property_id uuid not null references public.properties(id) on delete cascade, storage_path text not null, thumbnail_path text, display_order smallint not null default 0 check(display_order between 0 and 19), is_primary boolean not null default false, created_at timestamptz not null default now(), unique(property_id,display_order));
create unique index one_primary_image_per_property on public.property_images(property_id) where is_primary;
create table public.property_verifications (id uuid primary key default gen_random_uuid(), property_id uuid not null references public.properties(id) on delete cascade, verification_type text not null check(verification_type in ('identity','location','ownership_document','building_document')), status review_status not null default 'pending', reviewed_by uuid references public.profiles(id), notes text, document_storage_path text, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.favorites (user_id uuid references public.profiles(id) on delete cascade, property_id uuid references public.properties(id) on delete cascade, created_at timestamptz not null default now(), primary key(user_id,property_id));
create table public.inquiries (id uuid primary key default gen_random_uuid(), property_id uuid not null references public.properties(id), sender_id uuid not null references public.profiles(id), recipient_id uuid not null references public.profiles(id), message text not null check(length(message) between 1 and 2000), status text not null default 'new' check(status in ('new','read','responded','closed')), created_at timestamptz not null default now());
create table public.property_reports (id uuid primary key default gen_random_uuid(), property_id uuid not null references public.properties(id), reporter_id uuid not null references public.profiles(id), reason text not null check(reason in ('scam','duplicate_listing','incorrect_information','wrong_location','inappropriate_content','property_already_sold_rented','suspected_stolen_photographs','other')), description text check(length(description)<=2000), status text not null default 'open' check(status in ('open','reviewing','resolved','dismissed')), created_at timestamptz not null default now(), resolved_at timestamptz);
create table public.analytics_events (id bigint generated always as identity primary key, property_id uuid references public.properties(id) on delete cascade, user_id uuid references public.profiles(id) on delete set null, event_type text not null check(event_type in ('view','search','favorite','inquiry','phone_click','whatsapp_click','listing_creation','listing_publication','verification_status')), metadata jsonb not null default '{}', created_at timestamptz not null default now());
create table public.locations (id uuid primary key default gen_random_uuid(), city text not null, subcity text, neighborhood text not null, active boolean not null default true, unique(city,subcity,neighborhood));

create index properties_city_idx on public.properties(city); create index properties_subcity_idx on public.properties(subcity); create index properties_neighborhood_idx on public.properties(neighborhood); create index properties_type_idx on public.properties(property_type); create index properties_listing_type_idx on public.properties(listing_type); create index properties_price_idx on public.properties(price); create index properties_bedrooms_idx on public.properties(bedrooms); create index properties_area_idx on public.properties(area_sqm); create index properties_status_idx on public.properties(status); create index properties_verification_idx on public.properties(verification_status); create index properties_created_idx on public.properties(created_at desc); create index properties_geo_idx on public.properties(latitude,longitude); create index property_search_idx on public.properties(status,city,listing_type,property_type,price);

create or replace function public.is_admin() returns boolean language sql stable security definer set search_path='' as $$ select exists(select 1 from public.profiles where id=auth.uid() and role='admin' and suspended_at is null) $$;
alter table public.profiles enable row level security; alter table public.properties enable row level security; alter table public.property_images enable row level security; alter table public.property_verifications enable row level security; alter table public.favorites enable row level security; alter table public.inquiries enable row level security; alter table public.property_reports enable row level security; alter table public.analytics_events enable row level security; alter table public.locations enable row level security;
create policy "public profiles readable" on public.profiles for select using(suspended_at is null); create policy "own profile update" on public.profiles for update using(id=auth.uid()) with check(id=auth.uid() and role=(select role from public.profiles where id=auth.uid()));
create policy "published properties readable" on public.properties for select using(status='published' or owner_id=auth.uid() or public.is_admin()); create policy "sellers insert properties" on public.properties for insert with check(owner_id=auth.uid() and exists(select 1 from public.profiles where id=auth.uid() and role in ('owner','broker','admin') and suspended_at is null)); create policy "owners update properties" on public.properties for update using(owner_id=auth.uid() or public.is_admin()); create policy "owners delete properties" on public.properties for delete using(owner_id=auth.uid() or public.is_admin());
create policy "public published images" on public.property_images for select using(exists(select 1 from public.properties p where p.id=property_id and (p.status='published' or p.owner_id=auth.uid() or public.is_admin()))); create policy "owners manage images" on public.property_images for all using(exists(select 1 from public.properties p where p.id=property_id and (p.owner_id=auth.uid() or public.is_admin())));
create policy "admins access verifications" on public.property_verifications for all using(public.is_admin()) with check(public.is_admin()); create policy "owner sees checks without documents" on public.property_verifications for select using(document_storage_path is null and exists(select 1 from public.properties p where p.id=property_id and p.owner_id=auth.uid()));
create policy "own favorites" on public.favorites for all using(user_id=auth.uid()) with check(user_id=auth.uid()); create policy "inquiry participants" on public.inquiries for select using(sender_id=auth.uid() or recipient_id=auth.uid() or public.is_admin()); create policy "send inquiry" on public.inquiries for insert with check(sender_id=auth.uid()); create policy "recipient updates inquiry" on public.inquiries for update using(recipient_id=auth.uid() or public.is_admin()); create policy "submit reports" on public.property_reports for insert with check(reporter_id=auth.uid()); create policy "own or admin reports" on public.property_reports for select using(reporter_id=auth.uid() or public.is_admin()); create policy "admin resolves reports" on public.property_reports for update using(public.is_admin()); create policy "events insert" on public.analytics_events for insert with check(user_id is null or user_id=auth.uid()); create policy "owner analytics" on public.analytics_events for select using(public.is_admin() or exists(select 1 from public.properties p where p.id=property_id and p.owner_id=auth.uid())); create policy "locations public" on public.locations for select using(active); create policy "locations admin" on public.locations for all using(public.is_admin());

-- Public photos and private verification documents use separate buckets.
insert into storage.buckets(id,name,public,file_size_limit,allowed_mime_types) values ('property-images','property-images',true,10485760,array['image/jpeg','image/png','image/webp']),('verification-documents','verification-documents',false,15728640,array['image/jpeg','image/png','application/pdf']) on conflict(id) do nothing;
create policy "public property images storage" on storage.objects for select using(bucket_id='property-images'); create policy "authenticated image uploads" on storage.objects for insert to authenticated with check(bucket_id='property-images' and (storage.foldername(name))[1]=auth.uid()::text); create policy "owner image changes" on storage.objects for update to authenticated using(bucket_id='property-images' and owner_id=auth.uid()); create policy "owner image deletes" on storage.objects for delete to authenticated using(bucket_id='property-images' and owner_id=auth.uid()); create policy "admins read verification documents" on storage.objects for select to authenticated using(bucket_id='verification-documents' and public.is_admin()); create policy "owners submit verification documents" on storage.objects for insert to authenticated with check(bucket_id='verification-documents' and (storage.foldername(name))[1]=auth.uid()::text);
